    u = array[x + 0], v = array[x + 8];
    array[x + 0] = u + v;
    array[x + 8] = u - v;
    u = array[x + 1], v = array[x + 9];
    array[x + 1] = u + v;
    array[x + 9] = u - v;
    u = array[x + 2], v = array[x + 10];
    array[x + 2] = u + v;
    array[x + 10] = u - v;
    u = array[x + 3], v = array[x + 11];
    array[x + 3] = u + v;
    array[x + 11] = u - v;
    u = array[x + 4], v = array[x + 12];
    array[x + 4] = u + v;
    array[x + 12] = u - v;
    u = array[x + 5], v = array[x + 13];
    array[x + 5] = u + v;
    array[x + 13] = u - v;
    u = array[x + 6], v = array[x + 14];
    array[x + 6] = u + v;
    array[x + 14] = u - v;
    u = array[x + 7], v = array[x + 15];
    array[x + 7] = u + v;
    array[x + 15] = u - v;
