    u = array[x + 0], v = array[x + 32];
    array[x + 0] = u + v;
    array[x + 32] = u - v;
    u = array[x + 1], v = array[x + 33];
    array[x + 1] = u + v;
    array[x + 33] = u - v;
    u = array[x + 2], v = array[x + 34];
    array[x + 2] = u + v;
    array[x + 34] = u - v;
    u = array[x + 3], v = array[x + 35];
    array[x + 3] = u + v;
    array[x + 35] = u - v;
    u = array[x + 4], v = array[x + 36];
    array[x + 4] = u + v;
    array[x + 36] = u - v;
    u = array[x + 5], v = array[x + 37];
    array[x + 5] = u + v;
    array[x + 37] = u - v;
    u = array[x + 6], v = array[x + 38];
    array[x + 6] = u + v;
    array[x + 38] = u - v;
    u = array[x + 7], v = array[x + 39];
    array[x + 7] = u + v;
    array[x + 39] = u - v;
    u = array[x + 8], v = array[x + 40];
    array[x + 8] = u + v;
    array[x + 40] = u - v;
    u = array[x + 9], v = array[x + 41];
    array[x + 9] = u + v;
    array[x + 41] = u - v;
    u = array[x + 10], v = array[x + 42];
    array[x + 10] = u + v;
    array[x + 42] = u - v;
    u = array[x + 11], v = array[x + 43];
    array[x + 11] = u + v;
    array[x + 43] = u - v;
    u = array[x + 12], v = array[x + 44];
    array[x + 12] = u + v;
    array[x + 44] = u - v;
    u = array[x + 13], v = array[x + 45];
    array[x + 13] = u + v;
    array[x + 45] = u - v;
    u = array[x + 14], v = array[x + 46];
    array[x + 14] = u + v;
    array[x + 46] = u - v;
    u = array[x + 15], v = array[x + 47];
    array[x + 15] = u + v;
    array[x + 47] = u - v;
    u = array[x + 16], v = array[x + 48];
    array[x + 16] = u + v;
    array[x + 48] = u - v;
    u = array[x + 17], v = array[x + 49];
    array[x + 17] = u + v;
    array[x + 49] = u - v;
    u = array[x + 18], v = array[x + 50];
    array[x + 18] = u + v;
    array[x + 50] = u - v;
    u = array[x + 19], v = array[x + 51];
    array[x + 19] = u + v;
    array[x + 51] = u - v;
    u = array[x + 20], v = array[x + 52];
    array[x + 20] = u + v;
    array[x + 52] = u - v;
    u = array[x + 21], v = array[x + 53];
    array[x + 21] = u + v;
    array[x + 53] = u - v;
    u = array[x + 22], v = array[x + 54];
    array[x + 22] = u + v;
    array[x + 54] = u - v;
    u = array[x + 23], v = array[x + 55];
    array[x + 23] = u + v;
    array[x + 55] = u - v;
    u = array[x + 24], v = array[x + 56];
    array[x + 24] = u + v;
    array[x + 56] = u - v;
    u = array[x + 25], v = array[x + 57];
    array[x + 25] = u + v;
    array[x + 57] = u - v;
    u = array[x + 26], v = array[x + 58];
    array[x + 26] = u + v;
    array[x + 58] = u - v;
    u = array[x + 27], v = array[x + 59];
    array[x + 27] = u + v;
    array[x + 59] = u - v;
    u = array[x + 28], v = array[x + 60];
    array[x + 28] = u + v;
    array[x + 60] = u - v;
    u = array[x + 29], v = array[x + 61];
    array[x + 29] = u + v;
    array[x + 61] = u - v;
    u = array[x + 30], v = array[x + 62];
    array[x + 30] = u + v;
    array[x + 62] = u - v;
    u = array[x + 31], v = array[x + 63];
    array[x + 31] = u + v;
    array[x + 63] = u - v;
