    u = array[x + 0], v = array[x + 64];
    array[x + 0] = u + v;
    array[x + 64] = u - v;
    u = array[x + 1], v = array[x + 65];
    array[x + 1] = u + v;
    array[x + 65] = u - v;
    u = array[x + 2], v = array[x + 66];
    array[x + 2] = u + v;
    array[x + 66] = u - v;
    u = array[x + 3], v = array[x + 67];
    array[x + 3] = u + v;
    array[x + 67] = u - v;
    u = array[x + 4], v = array[x + 68];
    array[x + 4] = u + v;
    array[x + 68] = u - v;
    u = array[x + 5], v = array[x + 69];
    array[x + 5] = u + v;
    array[x + 69] = u - v;
    u = array[x + 6], v = array[x + 70];
    array[x + 6] = u + v;
    array[x + 70] = u - v;
    u = array[x + 7], v = array[x + 71];
    array[x + 7] = u + v;
    array[x + 71] = u - v;
    u = array[x + 8], v = array[x + 72];
    array[x + 8] = u + v;
    array[x + 72] = u - v;
    u = array[x + 9], v = array[x + 73];
    array[x + 9] = u + v;
    array[x + 73] = u - v;
    u = array[x + 10], v = array[x + 74];
    array[x + 10] = u + v;
    array[x + 74] = u - v;
    u = array[x + 11], v = array[x + 75];
    array[x + 11] = u + v;
    array[x + 75] = u - v;
    u = array[x + 12], v = array[x + 76];
    array[x + 12] = u + v;
    array[x + 76] = u - v;
    u = array[x + 13], v = array[x + 77];
    array[x + 13] = u + v;
    array[x + 77] = u - v;
    u = array[x + 14], v = array[x + 78];
    array[x + 14] = u + v;
    array[x + 78] = u - v;
    u = array[x + 15], v = array[x + 79];
    array[x + 15] = u + v;
    array[x + 79] = u - v;
    u = array[x + 16], v = array[x + 80];
    array[x + 16] = u + v;
    array[x + 80] = u - v;
    u = array[x + 17], v = array[x + 81];
    array[x + 17] = u + v;
    array[x + 81] = u - v;
    u = array[x + 18], v = array[x + 82];
    array[x + 18] = u + v;
    array[x + 82] = u - v;
    u = array[x + 19], v = array[x + 83];
    array[x + 19] = u + v;
    array[x + 83] = u - v;
    u = array[x + 20], v = array[x + 84];
    array[x + 20] = u + v;
    array[x + 84] = u - v;
    u = array[x + 21], v = array[x + 85];
    array[x + 21] = u + v;
    array[x + 85] = u - v;
    u = array[x + 22], v = array[x + 86];
    array[x + 22] = u + v;
    array[x + 86] = u - v;
    u = array[x + 23], v = array[x + 87];
    array[x + 23] = u + v;
    array[x + 87] = u - v;
    u = array[x + 24], v = array[x + 88];
    array[x + 24] = u + v;
    array[x + 88] = u - v;
    u = array[x + 25], v = array[x + 89];
    array[x + 25] = u + v;
    array[x + 89] = u - v;
    u = array[x + 26], v = array[x + 90];
    array[x + 26] = u + v;
    array[x + 90] = u - v;
    u = array[x + 27], v = array[x + 91];
    array[x + 27] = u + v;
    array[x + 91] = u - v;
    u = array[x + 28], v = array[x + 92];
    array[x + 28] = u + v;
    array[x + 92] = u - v;
    u = array[x + 29], v = array[x + 93];
    array[x + 29] = u + v;
    array[x + 93] = u - v;
    u = array[x + 30], v = array[x + 94];
    array[x + 30] = u + v;
    array[x + 94] = u - v;
    u = array[x + 31], v = array[x + 95];
    array[x + 31] = u + v;
    array[x + 95] = u - v;
    u = array[x + 32], v = array[x + 96];
    array[x + 32] = u + v;
    array[x + 96] = u - v;
    u = array[x + 33], v = array[x + 97];
    array[x + 33] = u + v;
    array[x + 97] = u - v;
    u = array[x + 34], v = array[x + 98];
    array[x + 34] = u + v;
    array[x + 98] = u - v;
    u = array[x + 35], v = array[x + 99];
    array[x + 35] = u + v;
    array[x + 99] = u - v;
    u = array[x + 36], v = array[x + 100];
    array[x + 36] = u + v;
    array[x + 100] = u - v;
    u = array[x + 37], v = array[x + 101];
    array[x + 37] = u + v;
    array[x + 101] = u - v;
    u = array[x + 38], v = array[x + 102];
    array[x + 38] = u + v;
    array[x + 102] = u - v;
    u = array[x + 39], v = array[x + 103];
    array[x + 39] = u + v;
    array[x + 103] = u - v;
    u = array[x + 40], v = array[x + 104];
    array[x + 40] = u + v;
    array[x + 104] = u - v;
    u = array[x + 41], v = array[x + 105];
    array[x + 41] = u + v;
    array[x + 105] = u - v;
    u = array[x + 42], v = array[x + 106];
    array[x + 42] = u + v;
    array[x + 106] = u - v;
    u = array[x + 43], v = array[x + 107];
    array[x + 43] = u + v;
    array[x + 107] = u - v;
    u = array[x + 44], v = array[x + 108];
    array[x + 44] = u + v;
    array[x + 108] = u - v;
    u = array[x + 45], v = array[x + 109];
    array[x + 45] = u + v;
    array[x + 109] = u - v;
    u = array[x + 46], v = array[x + 110];
    array[x + 46] = u + v;
    array[x + 110] = u - v;
    u = array[x + 47], v = array[x + 111];
    array[x + 47] = u + v;
    array[x + 111] = u - v;
    u = array[x + 48], v = array[x + 112];
    array[x + 48] = u + v;
    array[x + 112] = u - v;
    u = array[x + 49], v = array[x + 113];
    array[x + 49] = u + v;
    array[x + 113] = u - v;
    u = array[x + 50], v = array[x + 114];
    array[x + 50] = u + v;
    array[x + 114] = u - v;
    u = array[x + 51], v = array[x + 115];
    array[x + 51] = u + v;
    array[x + 115] = u - v;
    u = array[x + 52], v = array[x + 116];
    array[x + 52] = u + v;
    array[x + 116] = u - v;
    u = array[x + 53], v = array[x + 117];
    array[x + 53] = u + v;
    array[x + 117] = u - v;
    u = array[x + 54], v = array[x + 118];
    array[x + 54] = u + v;
    array[x + 118] = u - v;
    u = array[x + 55], v = array[x + 119];
    array[x + 55] = u + v;
    array[x + 119] = u - v;
    u = array[x + 56], v = array[x + 120];
    array[x + 56] = u + v;
    array[x + 120] = u - v;
    u = array[x + 57], v = array[x + 121];
    array[x + 57] = u + v;
    array[x + 121] = u - v;
    u = array[x + 58], v = array[x + 122];
    array[x + 58] = u + v;
    array[x + 122] = u - v;
    u = array[x + 59], v = array[x + 123];
    array[x + 59] = u + v;
    array[x + 123] = u - v;
    u = array[x + 60], v = array[x + 124];
    array[x + 60] = u + v;
    array[x + 124] = u - v;
    u = array[x + 61], v = array[x + 125];
    array[x + 61] = u + v;
    array[x + 125] = u - v;
    u = array[x + 62], v = array[x + 126];
    array[x + 62] = u + v;
    array[x + 126] = u - v;
    u = array[x + 63], v = array[x + 127];
    array[x + 63] = u + v;
    array[x + 127] = u - v;
