    u = array[x + 0], v = array[x + 16];
    array[x + 0] = u + v;
    array[x + 16] = u - v;
    u = array[x + 1], v = array[x + 17];
    array[x + 1] = u + v;
    array[x + 17] = u - v;
    u = array[x + 2], v = array[x + 18];
    array[x + 2] = u + v;
    array[x + 18] = u - v;
    u = array[x + 3], v = array[x + 19];
    array[x + 3] = u + v;
    array[x + 19] = u - v;
    u = array[x + 4], v = array[x + 20];
    array[x + 4] = u + v;
    array[x + 20] = u - v;
    u = array[x + 5], v = array[x + 21];
    array[x + 5] = u + v;
    array[x + 21] = u - v;
    u = array[x + 6], v = array[x + 22];
    array[x + 6] = u + v;
    array[x + 22] = u - v;
    u = array[x + 7], v = array[x + 23];
    array[x + 7] = u + v;
    array[x + 23] = u - v;
    u = array[x + 8], v = array[x + 24];
    array[x + 8] = u + v;
    array[x + 24] = u - v;
    u = array[x + 9], v = array[x + 25];
    array[x + 9] = u + v;
    array[x + 25] = u - v;
    u = array[x + 10], v = array[x + 26];
    array[x + 10] = u + v;
    array[x + 26] = u - v;
    u = array[x + 11], v = array[x + 27];
    array[x + 11] = u + v;
    array[x + 27] = u - v;
    u = array[x + 12], v = array[x + 28];
    array[x + 12] = u + v;
    array[x + 28] = u - v;
    u = array[x + 13], v = array[x + 29];
    array[x + 13] = u + v;
    array[x + 29] = u - v;
    u = array[x + 14], v = array[x + 30];
    array[x + 14] = u + v;
    array[x + 30] = u - v;
    u = array[x + 15], v = array[x + 31];
    array[x + 15] = u + v;
    array[x + 31] = u - v;
